### ISSUE TITLE
Error: invalid property requested: 'null'

### ISSUE THREAD

**Issue by comrat** [pureqml/qmlcore#133]
If you try to set 'null' to any anchor property (for example: `anchors.left: null;`) you will see corresponded error `qml initialization failed:  Error: invalid property requested: 'null'`

**Comment by whoozle** [comment]
fixed in 99fc29c537ab1a1a8c792c2f1f0c75baef33cc00

**Comment by comrat** [comment]
Still reproduced in runtime:
```
Item {   
   anchors.fill: parent;

   Button {
       z: 1;
       text: parent.action;
       onClicked: { this.parent.action = !this.parent.action }
   }

   property bool action;

   Rectangle {
       width: 100;
       height: 100;
       color: "lightgreen";
       anchors.right: parent.action ? parent.right : null;
   }
```
Click on button to see same error message

**Comment by whoozle** [comment]
fixed in fe5143d0ea5d1806b6c6e7841e28ac8a37e2b7d6
restore default position in cea2bb424c2ad974f268f0ea349212ec3d71d6a4

**Comment by whoozle** [comment]
consider restoring original values in the future (left + right -> width, left -> original width) situation
